version: '2.1'
services:

  registry:
    image: bsuir/metrics-registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: bsuir/metrics-gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      NOTIFICATION_SERVICE_PASSWORD: famcsn
      STATISTICS_SERVICE_PASSWORD: famcss
      ACCOUNT_SERVICE_PASSWORD: famcsa
      MONGODB_PASSWORD: famcsm
    image: bsuir/metrics-auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: famcsm
    image: bsuir/metrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  accounting-service:
    environment:
      ACCOUNT_SERVICE_PASSWORD: famcsa
      MONGODB_PASSWORD: famcsm
    image: bsuir/metrics-accounting-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  accounting-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: famcsm
    image: bsuir/metrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    environment:
      MONGODB_PASSWORD: famcsm
      STATISTICS_SERVICE_PASSWORD: famcss
    image: bsuir/metrics-statistics-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: famcsm
    image: bsuir/metrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    environment:
      MONGODB_PASSWORD: famcsm
      NOTIFICATION_SERVICE_PASSWORD: famcsn
    image: bsuir/metrics-notification-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-mongodb:
    image: bsuir/metrics-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD: famcsm
    logging:
      options:
        max-size: "10m"
        max-file: "10"
