version: '2.1'
services:

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017
    environment:
      MONGODB_PASSWORD: famcsm
    image: bsuir/metrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  accounting-mongodb:
    build: mongodb
    ports:
      - 26000:27017
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: famcsm
    image: bsuir/metrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017
    environment:
      MONGODB_PASSWORD: famcsm
    image: bsuir/metrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017
    image: bsuir/metrics-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD: famcsm
    logging:
      options:
        max-size: "10m"
        max-file: "10"