version: '2.1'
services:

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 9044:9044

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  accounting-service:
    build: accounting-service
    ports:
      - 9008:9008

  accounting-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  statistics-service:
    build: statistics-service
    ports:
      - 9009:9009

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  notification-service:
    build: notification-service
    ports:
      - 9006:9006

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017
